[project]
name = "primespiders"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "asgiref>=3.12.1",
    "dotenv>=0.9.9",
    "huey>=3.4.0",
    "pandas>=3.0.6",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pytest-playwright>=0.9.0",
    "redis>=8.1.0",
]

[dependency-groups]
dev = [
    "pytest-aio>=2.1.7",
    "pytest-cov>=7.1.0",
    "pytest-reportlog>=1.0.0",
    "pytest-timeout>=2.4.0",
    "ruff>=0.16.8",
]
