[project]
name = "primespiders"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "aiofiles>=25.1.0",
    "asgiref>=3.12.1",
    "dotenv>=0.9.9",
    "fastapi[standard]>=0.141.1",
    "fastmcp[apps]>=4.0.5",
    "httpx2>=2.13.0",
    "huey>=3.4.0",
    "pandas>=3.0.6",
    "pillow>=12.3.0",
    "psycopg2-binary>=2.9.13",
    "pydantic>=2.13.5",
    "pytest-playwright>=0.9.0",
    "python-crontab>=3.4.0",
    "redis>=8.1.0",
    "schedule>=1.2.2",
]

[dependency-groups]
dev = [
    "pytest-aio>=2.1.7",
    "pytest-cov>=7.1.0",
    "pytest-crayons>=0.0.9",
    "pytest-reportlog>=1.0.0",
    "pytest-timeout>=2.4.0",
    "ruff>=0.16.8",
]

[tool.pyright]
typeCheckingMode = "off"
reportMissingImports = true
reportUntypedBaseClass = true

[tool.pytest]
testpaths = ["tests"]
timeout="5000"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "api: marks tests as api tests",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests",
    "e2e: marks tests as end-to-end tests",
]

[tool.pytest_env]
env_files = [".env", ".env.test"]

[tool.autopep8]
max_line_length = 120
in-place = true
recursive = true
aggressive = 3

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

# For UV
[build-system]
requires = ["uv_build>=0.9,<0.10"]
build-backend = "uv_build"

